exercicios aula 1 pandas

In [1]:
import pandas as pd

1 - Realize os passos seguintes utilizando o mesmo dataset do íris da aula anterior ('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data').

a. Use o pandas para ler o arquivo como um dataframe. Obs: precisa ler o dataframe sem que a primeira linha corresponda ao nome das colunas.

In [8]:
dfiris = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data', header=None)

In [10]:
dfiris

       0    1    2    3               4
0    5.1  3.5  1.4  0.2     Iris-setosa
1    4.9  3.0  1.4  0.2     Iris-setosa
2    4.7  3.2  1.3  0.2     Iris-setosa
3    4.6  3.1  1.5  0.2     Iris-setosa
4    5.0  3.6  1.4  0.2     Iris-setosa
..   ...  ...  ...  ...             ...
145  6.7  3.0  5.2  2.3  Iris-virginica
146  6.3  2.5  5.0  1.9  Iris-virginica
147  6.5  3.0  5.2  2.0  Iris-virginica
148  6.2  3.4  5.4  2.3  Iris-virginica
149  5.9  3.0  5.1  1.8  Iris-virginica

[150 rows x 5 columns]

b. Sabendo que as cinco colunas correspondem, nessa ordem, a:

sepal length (cm)
sepal width (cm)
petal length (cm)
petal width (cm)
class:
Iris Setosa
Iris Versicolor
Iris Virginica
Leia novamente o arquivo passando o nome das colunas como argumento.

In [11]:
colunas = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'class']
dfiris = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data', header=None, names = colunas)

dfiris

     sepal_length  sepal_width  petal_length  petal_width           class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

c. Crie uma coluna para o volume sabendo que ele é calculado por (pi x petallength x sepal_length^2)/3

In [20]:
volume = ((dfiris.iloc[:,2]*dfiris.iloc[:,1]*3.14)**2)/3

In [21]:
volume

0        78.909665
1        57.974448
2        56.875431
3        71.063067
4        83.483205
          ...
145     799.810752
146     513.520833
147     799.810752
148    1107.856207
149     769.344588
Length: 150, dtype: float64

In [22]:
dfiris["volume"] = volume

In [23]:
dfiris

,sepal_length,sepal_width,petal_length,petal_width,class,volume
0,5.1,3.5,1.4,0.2,Iris-setosa,78.909665
1,4.9,3.0,1.4,0.2,Iris-setosa,57.974448
2,4.7,3.2,1.3,0.2,Iris-setosa,56.875431
3,4.6,3.1,1.5,0.2,Iris-setosa,71.063067
4,5.0,3.6,1.4,0.2,Iris-setosa,83.483205
...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,Iris-virginica,799.810752
146,6.3,2.5,5.0,1.9,Iris-virginica,513.520833
147,6.5,3.0,5.2,2.0,Iris-virginica,799.810752
148,6.2,3.4,5.4,2.3,Iris-virginica,1107.856207
149,5.9,3.0,5.1,1.8,Iris-virginica,769.344588

c. Calcule a média de cada atributo das flores.

In [25]:
dfiris.mean()

C:\Users\rodhe\AppData\Local\Temp/ipykernel_6296/2005626554.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  dfiris.mean()

sepal_length      5.843333
sepal_width       3.054000
petal_length      3.758667
petal_width       1.198667
volume          498.944644
dtype: float64

d. Novamente, calcule a média de cada atributo das flores só que agora faça-o separadamente para cada um dos tipos de íris indicados na coluna "class". Utilize o loop for para reduzir quantidade de linhas.
Existe diferença entre as médias de cada um dos atributos das flores?

e. Adicione uma nova coluna com o valor da média de 'sepal length' apenas para a íris da classe Iris-setosa.

f. Adicione uma coluna com a média de 'sepal length' de tal forma que cada tipo de íris tenha seu respectivo valor de média. Utilize o loop for e faça isso sem utilizar métodos que não foram ensinados na aula de hoje.